name: copper-staging

services:
  fuseki-plus:
    image: aksw/fuseki-plus:6.0.0
    init: true
    user: "${APP_UID}:${APP_GID}"
    environment:
      - JVM_ARGS=-Xmx16G -XX:ReplayDataFile=/run/log/fuseki_replay_pid%p.log -XX:ErrorFile=/run/log/fuseki_hs_err_pid%p.log -Dderby.stream.error.file=/run/log/fuseki_derby.log
      - JAVA_OPTIONS=-Xmx16G -XX:ReplayDataFile=/run/log/fuseki_replay_pid%p.log -XX:ErrorFile=/run/log/fuseki_hs_err_pid%p.log -Dderby.stream.error.file=/run/log/fuseki_derby.log
      - FUSEKI_BASE=/app/fuseki/run
    group_add:
      - "${DOCKER_GID}"
    volumes:
      - ./run:/app/fuseki/run
      - /var/run/docker.sock:/var/run/docker.sock
    # - /.data_nvme/coypu_nvme:/.data_nvme/coypu_nvme
    # working_dir: /data/coypu
    ports:
      - 3032:3030
      - 5005:5005
    restart: unless-stopped
    # network_mode: host
    networks:
      - coypu-net-staging

networks:
  coypu-net-staging:

